export const OPEN_CONTACT = "OPEN_CONTACT";
export const CLOSE_CONTACT = "CLOSE_CONTACT";

export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';

export const OPEN_CONFIRMATION = 'OPEN_CONFIRMATION';
export const CLOSE_CONFIRMATION = 'CLOSE_CONFIRMATION';

export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const CREATE_PORTFOLIO = 'CREATE_PORTFOLIO';
export const LOADING_PORTFOLIO = 'LOADING_PORTFOLIO';
export const GET_PORTFOLIO = 'GET_PORTFOLIO';
export const MODIFY_PORTFOLIO = 'MODIFY_PORTFOLIO';
export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO';

export const POSTS_ERROR = 'POSTS_ERROR';

